iphp:
  build: .
  volumes:
    - /c/Users/Me/docker-nginx-php-mysql-demo/public:/usr/share/nginx/html
  ports:
    - "9000:9000"
inginx:
  image: nginx
  volumes:
    - /c/Users/Me/docker-nginx-php-mysql-demo/nginx.conf:/etc/nginx/nginx.conf
    - /c/Users/Me/docker-nginx-php-mysql-demo/public:/usr/share/nginx/html
  ports:
    - "80:80"
imysql:
  image: mysql
  volumes: 
    - /c/Users/Me/docker-nginx-php-mysql-demo/mysql:/var/lib/mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
  ports:
    - "3308:3306"